version: "3.8"
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

  postgres_db:
    image: postgres:latest
    container_name: PostgresCont 
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data

  rabbit_postgre:
    image: drozhevskii/rabbit_postgre:latest
    links:
      - rabbitmq
      - postgres_db
    ports:
      - '5000:5000'
      
networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  postgres_db:
    driver: local